//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmoSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baixas
    {
        public Baixas()
        {
            this.ItensBaixa = new HashSet<ItensBaixa>();
        }
    
        public int idBaixas { get; set; }
        public string Descricao { get; set; }
        public string Departamento { get; set; }
        public Nullable<System.DateTime> DataBaixa { get; set; }
    
        public virtual ICollection<ItensBaixa> ItensBaixa { get; set; }
    }
}
