//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmoSharp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlmosharpEntities : DbContext
    {
        public AlmosharpEntities()
            : base("name=AlmosharpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Baixas> Baixas { get; set; }
        public DbSet<Entradas> Entradas { get; set; }
        public DbSet<ItensBaixa> ItensBaixa { get; set; }
        public DbSet<ItensEntrada> ItensEntrada { get; set; }
        public DbSet<Produtos> Produtos { get; set; }
    }
}
