//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmoSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItensBaixa
    {
        public int idItensBaixa { get; set; }
        public Nullable<int> Baixas_idBaixas { get; set; }
        public Nullable<int> Produtos_idProdutos { get; set; }
        public Nullable<int> Quantidade { get; set; }
    
        public virtual Baixas Baixas { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
