//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmoSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        public Produtos()
        {
            this.ItensBaixa = new HashSet<ItensBaixa>();
            this.ItensEntrada = new HashSet<ItensEntrada>();
        }
    
        public int idProdutos { get; set; }
        public string Nome { get; set; }
        public string Unidade { get; set; }
        public Nullable<int> Quantidade { get; set; }
    
        public virtual ICollection<ItensBaixa> ItensBaixa { get; set; }
        public virtual ICollection<ItensEntrada> ItensEntrada { get; set; }
    }
}
